require("dotenv").config();

const { test, describe, before, after } = require("node:test");
const assert = require("node:assert/strict");
const request = require("supertest");

const app = require("../app");
const { db } = require("../config/db");
const { sql } = require("drizzle-orm");
const { staffToken, closeDb } = require("./helpers");

/**
 * Raising an expense in a currency, and — the part that broke — taking the
 * rate back off one.
 *
 * A rate is optional on a foreign invoice: "USD 50,000, converted at nothing
 * yet" is a legitimate state, and an edit has to be able to return a row to it.
 * It could not. `pick()` is `body[snake] ?? body[camel]`, so the explicit null
 * that means "clear this" arrived as undefined, fell back to the rate already
 * on the row, and the edit silently did nothing — the field cleared on screen
 * and came back on reload.
 *
 * The distinction these tests hold down is between a field that was not sent
 * and a field that was sent empty. Everything else here is scaffolding.
 */

const EXPENSES = "/api/expenses";
const RUN = String(Date.now()).slice(-6);
const rowsOf = (r) => r.rows ?? r;

let token;
let categoryId;
const created = [];

/** The stored row, read past the API so the assertions are about the database. */
const rowById = async (id) => {
  const rows = rowsOf(
    await db.execute(sql`
      SELECT currency, exchange_rate, paid_exchange_rate, amount, amount_ngn
      FROM pfi_expenses WHERE id = ${id}
    `)
  );
  return rows[0];
};

describe("expense currency", () => {
  before(async () => {
    token = await staffToken(request, app);
    const rows = rowsOf(
      await db.execute(sql`
        SELECT id FROM expense_categories
        WHERE gl_group = 'general' AND is_active IS NOT FALSE
        ORDER BY id LIMIT 1
      `)
    );
    categoryId = rows[0]?.id;
  });

  after(async () => {
    if (created.length) {
      await db.execute(
        sql`DELETE FROM pfi_expenses WHERE id IN (${sql.join(created.map((id) => sql`${id}`), sql`, `)})`
      );
    }
    await closeDb();
  });

  const raise = async (body) => {
    const res = await request(app)
      .post(EXPENSES)
      .set("Authorization", `Bearer ${token}`)
      .send({ category_id: categoryId, description: `Currency ${RUN}`, ...body });
    if (res.body?.data?.expense?.id) created.push(res.body.data.expense.id);
    return res;
  };

  test("a dollar invoice with a rate carries its naira translation", async (t) => {
    if (!categoryId) return t.skip("no seeded general expense account in this database");

    const res = await raise({ amount: 50000, currency: "USD", exchange_rate: 1530 });
    assert.equal(res.status, 201, JSON.stringify(res.body));

    const row = await rowById(res.body.data.expense.id);
    assert.equal(row.currency, "USD");
    assert.equal(Number(row.exchange_rate), 1530);
    assert.equal(Number(row.amount), 50000);
    // Generated by the database from the two above — never written by the API.
    assert.equal(Number(row.amount_ngn), 76500000);
  });

  test("a dollar invoice with no rate has no naira value at all", async (t) => {
    if (!categoryId) return t.skip("no seeded general expense account in this database");

    const res = await raise({ amount: 50000, currency: "USD" });
    assert.equal(res.status, 201, JSON.stringify(res.body));

    const row = await rowById(res.body.data.expense.id);
    assert.equal(row.currency, "USD");
    assert.equal(row.exchange_rate, null);
    // Null, not zero and not the amount. A guess here is the whole bug class.
    assert.equal(row.amount_ngn, null);
  });

  test("clearing the rate leaves the invoice in its own currency", async (t) => {
    if (!categoryId) return t.skip("no seeded general expense account in this database");

    const res = await raise({ amount: 50000, currency: "USD", exchange_rate: 1530 });
    assert.equal(res.status, 201, JSON.stringify(res.body));
    const id = res.body.data.expense.id;

    const patch = await request(app)
      .patch(`${EXPENSES}/${id}`)
      .set("Authorization", `Bearer ${token}`)
      .send({ currency: "USD", exchange_rate: null });
    assert.equal(patch.status, 200, JSON.stringify(patch.body));

    const row = await rowById(id);
    assert.equal(row.currency, "USD", "still a dollar invoice");
    assert.equal(row.exchange_rate, null, "the rate is gone — this is the regression");
    assert.equal(row.paid_exchange_rate, null, "and the payment rate went with it");
    assert.equal(row.amount_ngn, null, "so there is no naira figure to report");
    assert.equal(Number(row.amount), 50000, "the debt itself is untouched");
  });

  test("an edit that does not mention the rate leaves it alone", async (t) => {
    if (!categoryId) return t.skip("no seeded general expense account in this database");

    const res = await raise({ amount: 50000, currency: "USD", exchange_rate: 1530 });
    const id = res.body.data.expense.id;

    // The other half of the distinction: absent must not read as cleared, or
    // editing a description would silently drop the rate.
    const patch = await request(app)
      .patch(`${EXPENSES}/${id}`)
      .set("Authorization", `Bearer ${token}`)
      .send({ description: `Renamed ${RUN}` });
    assert.equal(patch.status, 200, JSON.stringify(patch.body));

    const row = await rowById(id);
    assert.equal(Number(row.exchange_rate), 1530);
    assert.equal(Number(row.amount_ngn), 76500000);
  });

  test("adding a rate back converts it again", async (t) => {
    if (!categoryId) return t.skip("no seeded general expense account in this database");

    const res = await raise({ amount: 50000, currency: "USD" });
    const id = res.body.data.expense.id;

    const patch = await request(app)
      .patch(`${EXPENSES}/${id}`)
      .set("Authorization", `Bearer ${token}`)
      .send({ currency: "USD", exchange_rate: 1600 });
    assert.equal(patch.status, 200, JSON.stringify(patch.body));

    const row = await rowById(id);
    assert.equal(Number(row.exchange_rate), 1600);
    assert.equal(Number(row.amount_ngn), 80000000);
  });

  test("a naira expense refuses a rate", async (t) => {
    if (!categoryId) return t.skip("no seeded general expense account in this database");

    const res = await raise({ amount: 1000, currency: "NGN", exchange_rate: 1530 });
    assert.equal(res.status, 400, JSON.stringify(res.body));
  });
});
