module.exports = {
  staffRepo: require("./staff.repository"),
  staffScopeRepo: require("./staffScope.repository"),
  customerRepo: require("./customer.repository"),
  // The alternate numbers a customer can also sign in on. The primary stays
  // on customers.phone — see db/migrations/0019_customer_phone_numbers.sql.
  customerPhoneRepo: require("./customerPhone.repository"),
  contactRepo: require("./contact.repository"),
  // Customers and contacts as one list — see the header of the file for why
  // the two tables stay separate but the two PAGES did not.
  peopleRepo: require("./people.repository"),
  truckRepo: require("./truck.repository"),
  driverRepo: require("./driver.repository"),
  depotRepo: require("./depot.repository"),
  lpgStationRepo: require("./lpgStation.repository"),
  productRepo: require("./product.repository"),
  pfiRepo: require("./pfi.repository"),
  pfiExpenseRepo: require("./pfiExpense.repository"),
  orderRepo: require("./order.repository"),
  ticketRepo: require("./ticket.repository"),
  depositRepo: require("./deposit.repository"),
  deliveryCustomerRepo: require("./deliveryCustomer.repository"),
  deliveryNoteRepo: require("./deliveryNote.repository"),
  deliveryInventoryRepo: require("./deliveryInventory.repository"),
  deliverySaleRepo: require("./deliverySale.repository"),
  webhookEventRepo: require("./webhookEvent.repository"),
  sessionRepo: require("./session.repository"),
  customerOtpRepo: require("./customerOtp.repository"),
  auditLogRepo: require("./auditLog.repository"),
  orderTruckRepo: require("./orderTruck.repository"),
  orderPfiAllocationRepo: require("./orderPfiAllocation.repository"),
  customerIdentityRepo: require("./customerIdentity.repository"),
  auditEventRepo: require("./auditEvent.repository"),
  fleetTruckRepo: require("./fleetTruck.repository"),
  dailyReportRepo: require("./dailyReport.repository"),
  incidentRecordRepo: require("./incidentRecord.repository"),
  offlineSaleRepo: require("./offlineSale.repository"),
  dangoteProductRepo: require("./dangoteProduct.repository"),
  dangoteOrderRequestRepo: require("./dangoteOrderRequest.repository"),
  lpgOrderRequestRepo: require("./lpgOrderRequest.repository"),
  waSessionRepo: require("./waSession.repository"),
  waMessageRepo: require("./waMessage.repository"),
  bankAccountRepo: require("./bankAccount.repository"),
  vendorRepo: require("./vendor.repository"),
  expectedPaymentRepo: require("./expectedPayment.repository"),
  commissionRepo: require("./commission.repository"),
  customerLicenseRepo: require("./customerLicense.repository"),
  notificationRepo: require("./notification.repository"),
  deviceTokenRepo: require("./deviceToken.repository"),
  notificationPreferenceRepo: require("./notificationPreference.repository"),
  notificationDeliveryRepo: require("./notificationDelivery.repository"),
  messageTemplateRepo: require("./messageTemplate.repository"),
  messageCampaignRepo: require("./messageCampaign.repository"),
};
